# Generated by Django 5.0.2 on 2024-05-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='aadhaarNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
