# Generated by Django 5.0.2 on 2024-03-14 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_time_end',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_time_start',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
