# Generated by Django 5.0.2 on 2024-03-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_doctor_consultation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='aadhar_file',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='degree_certificate',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='experience_certificate',
        ),
        migrations.AddField(
            model_name='verification',
            name='aadhaarNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='experience',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='verification',
            name='licencecertificateImage',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/licence'),
        ),
        migrations.AddField(
            model_name='verification',
            name='qualificationImage',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/qualification'),
        ),
        migrations.AddField(
            model_name='verification',
            name='register_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
