# Generated by Django 5.0.2 on 2024-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_verification_aadhar_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='experience',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
