# Generated by Django 5.0.2 on 2024-03-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_verification_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='is_KYC_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
