# Generated by Django 5.0.2 on 2024-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verification_is_kyc_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Ophthalmologist', 'Ophthalmologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Endocrinologist', 'Endocrinologist'), ('Pulmonologist', 'Pulmonologist'), ('Nephrologist', 'Nephrologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('General', 'General'), ('gynecologist', 'Gynecologist'), ('Radiologist', 'Radiologist')], default='General', max_length=30),
        ),
    ]
