# Generated by Django 4.2.7 on 2024-04-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_roomforchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomForChat',
        ),
    ]
