# Generated by Django 5.0.2 on 2024-04-01 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='end_day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_day',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
