# Generated by Django 5.0.2 on 2024-04-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_slot_start_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='end_day',
        ),
    ]
