# Generated by Django 5.0.2 on 2024-04-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_slot_end_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_cancelled',
        ),
    ]
