# Generated by Django 4.2.7 on 2024-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_consultency_completed',
            field=models.BooleanField(default=False),
        ),
    ]
