# Generated by Django 4.2.7 on 2024-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_transaction_is_consultency_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_consultency_completed',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20),
        ),
    ]
