# Generated by Django 4.2.7 on 2024-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.TextField(default='Visited For Heart Surgery'),
        ),
    ]
