# Generated by Django 4.2.7 on 2024-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_review_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescription/'),
        ),
    ]
