# Generated by Django 4.2.7 on 2024-04-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_prescription'),
        ('booking', '0012_transaction_prescription'),
    ]

    operations = [
    ]
