# Generated by Django 4.2.7 on 2024-04-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone_number'),
        ('booking', '0013_merge_0012_prescription_0012_transaction_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_given', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to='accounts.patient'),
        ),
    ]
