# Generated by Django 4.2.7 on 2024-04-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_transaction_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Age',
            field=models.IntegerField(default=21),
        ),
    ]
