# Generated by Django 5.0.2 on 2024-05-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_transactioncommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncommission',
            name='doctor_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
